version: "3"

services:
  tf-pose:
    image: tf-pose
    build: .
    container_name: tf-pose
    command: bash -c "cd /ros/src/tf-pose-estimation && pipenv run bash -c 'source /ros/devel/setup.bash;roslaunch tfpose_ros tfpose.launch'"
    runtime: nvidia
    tty: true
    volumes:
      - ${PWD}:/ros/src/tf-pose-estimation
    network_mode: "host"
